# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6501ddb5dcfd04d1fbfaac113385f06837a6593f8b15f4196c5bb53ed8d1f323d6dc25ec529e69dc6583539e629dcbe3f25398c63a1db6fe86f0586978767d0

test:
  secret_key_base: a02a180a6823851cbea8a99cec05e773016aa0aa1064204348f5a43be46f827c4ec9d29fa63dea4550462c5da741c6fca296c93291fc030c8f03285294d6bc70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
